apiVersion: v1
kind: ReplicationController
metadata:
 name: mytomcatcontainer-rc
spec:
 replicas: 2
 selector: 
  app: tcontainer
template:
 metadata:
  labels: 
   app: tcontainer
 spec:
  containers:
   - name: tomcatcontainer
     image: tomcat:9.0.93-jre8
     ports: 
     - containers: 8080