apiVersion: v1
kind: ReplicationController
metadata:
 name: 

spec:
 replicas:
 selector:
 

template:
 metadata:
   labels:
    app:
    
 spec:
  containers:
  - name:
    image:
    ports: 
    - container