apiVersion: v1
kind: Pod
metadata:
  name: hello-pod2
  labels:
    app: hello-pod2
spec:
  containers:
    - name: first-container
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hello-pod-service
spec:
  selector:
    app: hello-pod2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  
